/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XcokAmbulanceWlList {
    }
}
declare global {
    interface HTMLXcokAmbulanceWlListElement extends Components.XcokAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLXcokAmbulanceWlListElement: {
        prototype: HTMLXcokAmbulanceWlListElement;
        new (): HTMLXcokAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "xcok-ambulance-wl-list": HTMLXcokAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface XcokAmbulanceWlList {
    }
    interface IntrinsicElements {
        "xcok-ambulance-wl-list": XcokAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xcok-ambulance-wl-list": LocalJSX.XcokAmbulanceWlList & JSXBase.HTMLAttributes<HTMLXcokAmbulanceWlListElement>;
        }
    }
}
